# Code generated by scripts/sync_external_ingestion_contract.mjs. DO NOT EDIT.

from enum import StrEnum
from typing import Final, NamedTuple


class KnownErrorReason(StrEnum):
    AUTHORIZATION_DEPENDENCY_UNAVAILABLE = "AUTHORIZATION_DEPENDENCY_UNAVAILABLE"
    BACKPRESSURE = "BACKPRESSURE"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    FEATURE_NOT_ENTITLED = "FEATURE_NOT_ENTITLED"
    IDEMPOTENCY_MISMATCH = "IDEMPOTENCY_MISMATCH"
    INTEGRATION_UNAVAILABLE = "INTEGRATION_UNAVAILABLE"
    WORKSPACE_SELECTOR_CONFLICT = "WORKSPACE_SELECTOR_CONFLICT"


class ErrorReasonPolicy(NamedTuple):
    consumer_category: str
    grpc_code: str
    retry_classification: str
    reuse_idempotency_key: bool


KNOWN_ERROR_DOMAIN: Final = "medallion.jimtech.io"

REASON_POLICIES: Final[dict[KnownErrorReason, ErrorReasonPolicy]] = {
    KnownErrorReason.AUTHORIZATION_DEPENDENCY_UNAVAILABLE: ErrorReasonPolicy(
        consumer_category="transient_authorization_dependency",
        grpc_code="UNAVAILABLE",
        retry_classification="bounded_transient_retry",
        reuse_idempotency_key=True,
    ),
    KnownErrorReason.BACKPRESSURE: ErrorReasonPolicy(
        consumer_category="transient_backpressure",
        grpc_code="RESOURCE_EXHAUSTED",
        retry_classification="bounded_transient_retry",
        reuse_idempotency_key=True,
    ),
    KnownErrorReason.CAPABILITY_UNAVAILABLE: ErrorReasonPolicy(
        consumer_category="capability_disabled",
        grpc_code="FAILED_PRECONDITION",
        retry_classification="retry_after_configuration_or_entitlement_change",
        reuse_idempotency_key=True,
    ),
    KnownErrorReason.FEATURE_NOT_ENTITLED: ErrorReasonPolicy(
        consumer_category="entitlement_denied",
        grpc_code="FAILED_PRECONDITION",
        retry_classification="retry_after_configuration_or_entitlement_change",
        reuse_idempotency_key=True,
    ),
    KnownErrorReason.IDEMPOTENCY_MISMATCH: ErrorReasonPolicy(
        consumer_category="idempotency_conflict",
        grpc_code="ALREADY_EXISTS",
        retry_classification="terminal",
        reuse_idempotency_key=False,
    ),
    KnownErrorReason.INTEGRATION_UNAVAILABLE: ErrorReasonPolicy(
        consumer_category="transient_integration",
        grpc_code="UNAVAILABLE",
        retry_classification="bounded_transient_retry_idempotent_operations_only",
        reuse_idempotency_key=True,
    ),
    KnownErrorReason.WORKSPACE_SELECTOR_CONFLICT: ErrorReasonPolicy(
        consumer_category="workspace_selector_invalid",
        grpc_code="INVALID_ARGUMENT",
        retry_classification="terminal",
        reuse_idempotency_key=False,
    ),
}
