syntax = "proto2";

package buf.validate;

import "google/protobuf/descriptor.proto";

option go_package = "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate";

message StringRules {
  optional uint64 min_len = 2;
  optional uint64 max_bytes = 5;
  optional string pattern = 6;
}

message BytesRules {
  optional uint64 min_len = 2;
}

message Int64Rules {
  oneof greater_than {
    int64 gt = 4;
    int64 gte = 5;
  }
}

message UInt32Rules {
  optional uint32 lte = 3;
}

message RepeatedRules {
  optional uint64 min_items = 1;
  optional uint64 max_items = 2;
}

message FieldRules {
  oneof type {
    Int64Rules int64 = 4;
    UInt32Rules uint32 = 5;
    StringRules string = 14;
    BytesRules bytes = 15;
    RepeatedRules repeated = 18;
  }

  optional bool required = 25;
}

extend google.protobuf.FieldOptions {
  optional FieldRules field = 1159;
}
