// Code generated by scripts/sync_external_ingestion_contract.mjs. DO NOT EDIT.

package medallion

// KnownErrorReason is a stable ErrorInfo reason from the external-ingestion contract.
type KnownErrorReason string

const (
	// ErrorInfoDomain is the canonical google.rpc.ErrorInfo domain.
	ErrorInfoDomain = "medallion.jimtech.io"

	ErrorReasonAuthorizationDependencyUnavailable KnownErrorReason = "AUTHORIZATION_DEPENDENCY_UNAVAILABLE"
	ErrorReasonBackpressure                       KnownErrorReason = "BACKPRESSURE"
	ErrorReasonCapabilityUnavailable              KnownErrorReason = "CAPABILITY_UNAVAILABLE"
	ErrorReasonFeatureNotEntitled                 KnownErrorReason = "FEATURE_NOT_ENTITLED"
	ErrorReasonIdempotencyMismatch                KnownErrorReason = "IDEMPOTENCY_MISMATCH"
	ErrorReasonIntegrationUnavailable             KnownErrorReason = "INTEGRATION_UNAVAILABLE"
	ErrorReasonWorkspaceSelectorConflict          KnownErrorReason = "WORKSPACE_SELECTOR_CONFLICT"
)

type generatedErrorReasonPolicy struct {
	ConsumerCategory    string
	GRPCCode            string
	RetryClassification string
	ReuseIdempotencyKey bool
}

var generatedErrorReasonPolicies = map[KnownErrorReason]generatedErrorReasonPolicy{
	ErrorReasonAuthorizationDependencyUnavailable: {
		ConsumerCategory:    "transient_authorization_dependency",
		GRPCCode:            "UNAVAILABLE",
		RetryClassification: "bounded_transient_retry",
		ReuseIdempotencyKey: true,
	},
	ErrorReasonBackpressure: {
		ConsumerCategory:    "transient_backpressure",
		GRPCCode:            "RESOURCE_EXHAUSTED",
		RetryClassification: "bounded_transient_retry",
		ReuseIdempotencyKey: true,
	},
	ErrorReasonCapabilityUnavailable: {
		ConsumerCategory:    "capability_disabled",
		GRPCCode:            "FAILED_PRECONDITION",
		RetryClassification: "retry_after_configuration_or_entitlement_change",
		ReuseIdempotencyKey: true,
	},
	ErrorReasonFeatureNotEntitled: {
		ConsumerCategory:    "entitlement_denied",
		GRPCCode:            "FAILED_PRECONDITION",
		RetryClassification: "retry_after_configuration_or_entitlement_change",
		ReuseIdempotencyKey: true,
	},
	ErrorReasonIdempotencyMismatch: {
		ConsumerCategory:    "idempotency_conflict",
		GRPCCode:            "ALREADY_EXISTS",
		RetryClassification: "terminal",
		ReuseIdempotencyKey: false,
	},
	ErrorReasonIntegrationUnavailable: {
		ConsumerCategory:    "transient_integration",
		GRPCCode:            "UNAVAILABLE",
		RetryClassification: "bounded_transient_retry_idempotent_operations_only",
		ReuseIdempotencyKey: true,
	},
	ErrorReasonWorkspaceSelectorConflict: {
		ConsumerCategory:    "workspace_selector_invalid",
		GRPCCode:            "INVALID_ARGUMENT",
		RetryClassification: "terminal",
		ReuseIdempotencyKey: false,
	},
}
