import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const SDK_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_METAFILE = join(SDK_ROOT, "dist", "metafile-cjs.json");
const DEFAULT_OUTPUT = join(SDK_ROOT, "dist", "THIRD_PARTY_LICENSES.txt");
const LEGAL_FILE = /^(?:licen[cs]e|copying|notice)(?:$|[._-])/i;
const LICENSE_FILE = /^(?:licen[cs]e|copying)(?:$|[._-])/i;
const SPDX_OPERATORS = new Set(["AND", "OR", "WITH"]);
const FALLBACK_LICENSES = new Set(["Apache-2.0", "BSD-3-Clause"]);
const DIVIDER = "=".repeat(79);

export function buildThirdPartyLicenseInventory({
  sdkRoot = SDK_ROOT,
  metafilePath = DEFAULT_METAFILE,
} = {}) {
  const packages = bundledPackages(sdkRoot, metafilePath);
  const ownLegalSources = new Map(
    packages.map((item) => [item.id, legalSources(item)]),
  );
  const embeddedSources = new Map(
    packages.map((item) => [item.id, embeddedLegalSources(item)]),
  );
  const apacheSource = canonicalApacheSource(packages, ownLegalSources);

  const rendered = [
    "Medallion SDK bundled third-party licenses",
    "",
    "Generated by scripts/generate_third_party_licenses.mjs from the esbuild",
    "metafile for dist/index.cjs. Do not edit this file manually.",
    "",
    "Only packages with code embedded in the shipped CommonJS bundle are listed.",
    "Dependencies loaded externally retain the license files in their own packages.",
    "When a package omits a standalone license file, the labeled section uses",
    "canonical text from another bundled dependency's installed license file or",
    "a complete license notice embedded in that package's contributing source.",
    "",
    `Bundled packages: ${packages.length}`,
    "",
  ];

  for (const item of packages) {
    const sources = ownLegalSources.get(item.id) ?? [];
    const licenseSources = sources.filter((source) => source.isLicense);
    const noticeSources = sources.filter((source) => !source.isLicense);
    const embedded = embeddedSources.get(item.id) ?? [];

    if (licenseSources.length === 0) {
      licenseSources.push(
        ...fallbackLicenseSources(item, apacheSource, embedded),
      );
    }

    rendered.push(
      DIVIDER,
      `Package: ${item.name}`,
      `Version: ${item.version}`,
      `License: ${item.license}`,
      `Bundled input files: ${item.inputs.length}`,
      "",
    );

    const renderedSources = uniqueSources([
      ...licenseSources,
      ...embedded,
      ...noticeSources,
    ]);
    for (const source of renderedSources) {
      rendered.push(
        `----- BEGIN ${source.label} -----`,
        source.text.trimEnd(),
        `----- END ${source.label} -----`,
        "",
      );
    }
  }

  return {
    packages: packages.map(({ id, name, version, license, inputs }) => ({
      id,
      name,
      version,
      license,
      inputs: [...inputs],
    })),
    text: `${rendered.join("\n").trimEnd()}\n`,
  };
}

export function writeThirdPartyLicenses({
  sdkRoot = SDK_ROOT,
  metafilePath = DEFAULT_METAFILE,
  outputPath = DEFAULT_OUTPUT,
} = {}) {
  const inventory = buildThirdPartyLicenseInventory({ sdkRoot, metafilePath });
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, inventory.text, "utf8");
  return inventory;
}

export function checkThirdPartyLicenses({
  sdkRoot = SDK_ROOT,
  metafilePath = DEFAULT_METAFILE,
  outputPath = DEFAULT_OUTPUT,
} = {}) {
  const inventory = buildThirdPartyLicenseInventory({ sdkRoot, metafilePath });
  if (!existsSync(outputPath)) {
    throw new Error(`${displayPath(sdkRoot, outputPath)} is missing`);
  }
  if (readFileSync(outputPath, "utf8") !== inventory.text) {
    throw new Error(
      `${displayPath(sdkRoot, outputPath)} is stale; run pnpm build`,
    );
  }
  return inventory;
}

function bundledPackages(sdkRoot, metafilePath) {
  const metafile = parseJsonFile(metafilePath, "esbuild metafile");
  if (!isObject(metafile.outputs)) {
    throw new Error("esbuild metafile has no outputs object");
  }

  const bundleOutputs = Object.entries(metafile.outputs).filter(([output]) => {
    const normalized = normalizePath(output);
    return (
      normalized === "dist/index.cjs" || normalized.endsWith("/dist/index.cjs")
    );
  });
  if (bundleOutputs.length !== 1) {
    throw new Error(
      `esbuild metafile must describe exactly one dist/index.cjs output; got ${bundleOutputs.length}`,
    );
  }

  const output = bundleOutputs[0][1];
  if (!isObject(output) || !isObject(output.inputs)) {
    throw new Error("dist/index.cjs metafile output has no inputs object");
  }

  const nodeModulesRoot = resolve(sdkRoot, "node_modules");
  const byId = new Map();
  for (const [input, contribution] of Object.entries(output.inputs)) {
    if (
      !isObject(contribution) ||
      typeof contribution.bytesInOutput !== "number" ||
      contribution.bytesInOutput <= 0
    ) {
      continue;
    }

    const absoluteInput = isAbsolute(input)
      ? resolve(input)
      : resolve(sdkRoot, input);
    if (!isWithin(nodeModulesRoot, absoluteInput)) continue;

    const packageRoot = findPackageRoot(nodeModulesRoot, absoluteInput);
    const metadata = parseJsonFile(
      join(packageRoot, "package.json"),
      `package metadata for ${normalizePath(input)}`,
    );
    if (
      typeof metadata.name !== "string" ||
      metadata.name.length === 0 ||
      typeof metadata.version !== "string" ||
      metadata.version.length === 0 ||
      typeof metadata.license !== "string" ||
      metadata.license.length === 0
    ) {
      throw new Error(
        `${normalizePath(relative(sdkRoot, packageRoot))}/package.json must declare string name, version, and license fields`,
      );
    }

    const id = `${metadata.name}@${metadata.version}`;
    let item = byId.get(id);
    if (item === undefined) {
      item = {
        id,
        name: metadata.name,
        version: metadata.version,
        license: metadata.license,
        roots: new Set(),
        inputs: [],
      };
      byId.set(id, item);
    } else if (item.license !== metadata.license) {
      throw new Error(`${id} has conflicting license metadata`);
    }

    item.roots.add(packageRoot);
    item.inputs.push(normalizePath(relative(packageRoot, absoluteInput)));
  }

  const packages = [...byId.values()].sort((left, right) =>
    compare(left.id, right.id),
  );
  if (packages.length === 0) {
    throw new Error("dist/index.cjs does not contain any bundled npm packages");
  }
  for (const item of packages) {
    item.inputs = [...new Set(item.inputs)].sort(compare);
  }
  return packages;
}

function findPackageRoot(nodeModulesRoot, input) {
  let cursor = statSync(input).isDirectory() ? input : dirname(input);
  while (isWithin(nodeModulesRoot, cursor)) {
    const packageJson = join(cursor, "package.json");
    if (existsSync(packageJson) && statSync(packageJson).isFile()) {
      const metadata = parseJsonFile(
        packageJson,
        `package metadata for ${normalizePath(input)}`,
      );
      if (
        typeof metadata.name === "string" &&
        typeof metadata.version === "string" &&
        typeof metadata.license === "string"
      ) {
        return cursor;
      }
    }
    const parent = dirname(cursor);
    if (parent === cursor) break;
    cursor = parent;
  }
  throw new Error(
    `could not locate package.json for bundled input ${normalizePath(input)}`,
  );
}

function legalSources(item) {
  const byName = new Map();
  for (const packageRoot of [...item.roots].sort(compare)) {
    for (const entry of readdirSync(packageRoot, { withFileTypes: true })) {
      if (!entry.isFile() || !LEGAL_FILE.test(entry.name)) continue;
      const text = normalizedText(
        readFileSync(join(packageRoot, entry.name), "utf8"),
      );
      if (text.trim().length === 0) {
        throw new Error(`${item.id}/${entry.name} is empty`);
      }
      const existing = byName.get(entry.name);
      if (existing !== undefined && existing.text !== text) {
        throw new Error(
          `${item.id}/${entry.name} differs between package roots`,
        );
      }
      byName.set(entry.name, {
        isLicense: LICENSE_FILE.test(entry.name),
        label: `${item.id}/${entry.name}`,
        text,
      });
    }
  }
  return [...byName.values()].sort((left, right) =>
    compare(left.label, right.label),
  );
}

function canonicalApacheSource(packages, ownLegalSources) {
  const candidates = [];
  for (const item of packages) {
    if (item.license !== "Apache-2.0") continue;
    for (const source of ownLegalSources.get(item.id) ?? []) {
      if (
        source.isLicense &&
        source.text.includes("Apache License") &&
        source.text.includes("Version 2.0")
      ) {
        candidates.push(source);
      }
    }
  }
  candidates.sort((left, right) => compare(left.label, right.label));
  return candidates[0];
}

function fallbackLicenseSources(item, apacheSource, embeddedSources) {
  const licenseIds = parseFallbackLicenseIds(item.license);
  const sources = [];
  for (const licenseId of licenseIds) {
    if (licenseId === "Apache-2.0") {
      if (apacheSource === undefined) {
        throw new Error(
          `${item.id} does not publish a license file and no bundled dependency provides canonical Apache-2.0 text`,
        );
      }
      sources.push({
        isLicense: true,
        label: `${apacheSource.label} (canonical Apache-2.0 text for ${item.id})`,
        text: apacheSource.text,
      });
      continue;
    }

    if (licenseId === "BSD-3-Clause") {
      const source = embeddedSources.find(
        (candidate) => candidate.licenseId === "BSD-3-Clause",
      );
      if (source === undefined) {
        throw new Error(
          `${item.id} does not publish a license file and no bundled source contains its full BSD-3-Clause notice`,
        );
      }
      sources.push(source);
      continue;
    }

    throw new Error(
      `${item.id} does not publish a license file; unsupported fallback ${licenseId}`,
    );
  }
  return sources;
}

function parseFallbackLicenseIds(expression) {
  const tokens = expression.match(/[A-Za-z0-9.+-]+/g) ?? [];
  const ids = [];
  for (const token of tokens) {
    if (SPDX_OPERATORS.has(token)) continue;
    if (!FALLBACK_LICENSES.has(token)) {
      throw new Error(
        `cannot source full license text for unsupported expression ${expression}`,
      );
    }
    if (!ids.includes(token)) ids.push(token);
  }
  if (ids.length === 0) {
    throw new Error(`license expression ${expression} contains no license IDs`);
  }
  return ids;
}

function embeddedLegalSources(item) {
  const byText = new Map();
  for (const packageRoot of [...item.roots].sort(compare)) {
    for (const input of item.inputs) {
      const inputPath = resolve(packageRoot, input);
      if (
        !isWithin(packageRoot, inputPath) ||
        !existsSync(inputPath) ||
        !statSync(inputPath).isFile()
      ) {
        continue;
      }
      const notice = extractEmbeddedLegalNotice(
        readFileSync(inputPath, "utf8"),
      );
      if (notice === undefined || byText.has(notice.text)) continue;
      byText.set(notice.text, {
        isLicense: true,
        label: `${item.id}/${input} (embedded ${notice.licenseId} notice)`,
        licenseId: notice.licenseId,
        text: notice.text,
      });
    }
  }
  return [...byText.values()].sort((left, right) =>
    compare(left.label, right.label),
  );
}

function extractEmbeddedLegalNotice(raw) {
  const lines = normalizedText(raw).split("\n");
  for (let start = 0; start < lines.length; start += 1) {
    if (!/^\s*\/\/\s*Copyright\b/.test(lines[start])) continue;
    const comment = [];
    for (let index = start; index < lines.length; index += 1) {
      const match = lines[index].match(/^\s*\/\/(?:\s?(.*))?$/);
      if (match === null) break;
      comment.push(match[1] ?? "");
    }
    const notice = classifiedNotice(`${comment.join("\n").trimEnd()}\n`);
    if (notice !== undefined) return notice;
  }

  for (const match of normalizedText(raw).matchAll(/\/\*+([\s\S]*?)\*\//g)) {
    const text = `${(match[1] ?? "")
      .split("\n")
      .map((line) => line.replace(/^\s*\*? ?/, ""))
      .join("\n")
      .trim()}\n`;
    const notice = classifiedNotice(text);
    if (notice !== undefined) return notice;
  }
  return undefined;
}

function classifiedNotice(text) {
  if (
    text.includes("Redistribution and use in source and binary forms") &&
    text.includes("Neither the name") &&
    text.includes("THIS SOFTWARE IS PROVIDED")
  ) {
    return { licenseId: "BSD-3-Clause", text };
  }
  if (
    text.includes("Permission is hereby granted, free of charge") &&
    text.includes("The above copyright notice and this permission notice") &&
    text.includes("THE SOFTWARE IS PROVIDED")
  ) {
    return { licenseId: "MIT", text };
  }
  if (
    text.includes("Permission to use, copy, modify, and/or distribute") &&
    text.includes("with or without fee is hereby granted") &&
    text.includes("THE SOFTWARE IS PROVIDED")
  ) {
    return { licenseId: "ISC", text };
  }
  return undefined;
}

function uniqueSources(sources) {
  const byLabel = new Map();
  for (const source of sources) {
    if (!byLabel.has(source.label)) byLabel.set(source.label, source);
  }
  return [...byLabel.values()];
}

function parseJsonFile(path, label) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    throw new Error(`${label} is missing or invalid JSON`, { cause: error });
  }
}

function isWithin(parent, child) {
  const path = relative(parent, child);
  return (
    path !== "" &&
    path !== ".." &&
    !path.startsWith(`..${sep}`) &&
    !isAbsolute(path)
  );
}

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function normalizedText(text) {
  return text.replace(/\r\n?/g, "\n");
}

function normalizePath(path) {
  return path.split(sep).join("/");
}

function displayPath(root, path) {
  const displayed = relative(root, path);
  return normalizePath(displayed.length > 0 ? displayed : path);
}

function compare(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function runCli() {
  const args = process.argv.slice(2);
  if (args.length !== 1 || (args[0] !== "--check" && args[0] !== "--write")) {
    throw new Error(
      "usage: node scripts/generate_third_party_licenses.mjs --check|--write",
    );
  }
  const inventory =
    args[0] === "--write"
      ? writeThirdPartyLicenses()
      : checkThirdPartyLicenses();
  const verb = args[0] === "--write" ? "generated" : "verified";
  console.log(
    `${verb} dist/THIRD_PARTY_LICENSES.txt for ${inventory.packages.length} bundled packages`,
  );
}

const entryPoint = process.argv[1];
if (
  entryPoint !== undefined &&
  import.meta.url === pathToFileURL(resolve(entryPoint)).href
) {
  try {
    runCli();
  } catch (error) {
    console.error(
      `third-party license inventory failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    process.exitCode = 1;
  }
}
