// Code generated by scripts/sync_external_ingestion_contract.mjs. DO NOT EDIT.
// Source: sealed external-ingestion error registry.

export const MEDALLION_ERROR_INFO_DOMAIN = "medallion.jimtech.io" as const;

export const MEDALLION_ERROR_REASON_POLICY = {
  AUTHORIZATION_DEPENDENCY_UNAVAILABLE: {
    consumerCategory: "transient_authorization_dependency",
    grpcCode: "UNAVAILABLE",
    retryClassification: "bounded_transient_retry",
    reuseIdempotencyKey: true,
  },
  BACKPRESSURE: {
    consumerCategory: "transient_backpressure",
    grpcCode: "RESOURCE_EXHAUSTED",
    retryClassification: "bounded_transient_retry",
    reuseIdempotencyKey: true,
  },
  CAPABILITY_UNAVAILABLE: {
    consumerCategory: "capability_disabled",
    grpcCode: "FAILED_PRECONDITION",
    retryClassification: "retry_after_configuration_or_entitlement_change",
    reuseIdempotencyKey: true,
  },
  FEATURE_NOT_ENTITLED: {
    consumerCategory: "entitlement_denied",
    grpcCode: "FAILED_PRECONDITION",
    retryClassification: "retry_after_configuration_or_entitlement_change",
    reuseIdempotencyKey: true,
  },
  IDEMPOTENCY_MISMATCH: {
    consumerCategory: "idempotency_conflict",
    grpcCode: "ALREADY_EXISTS",
    retryClassification: "terminal",
    reuseIdempotencyKey: false,
  },
  INTEGRATION_UNAVAILABLE: {
    consumerCategory: "transient_integration",
    grpcCode: "UNAVAILABLE",
    retryClassification: "bounded_transient_retry_idempotent_operations_only",
    reuseIdempotencyKey: true,
  },
  WORKSPACE_SELECTOR_CONFLICT: {
    consumerCategory: "workspace_selector_invalid",
    grpcCode: "INVALID_ARGUMENT",
    retryClassification: "terminal",
    reuseIdempotencyKey: false,
  },
} as const;

export type MedallionKnownErrorReason =
  keyof typeof MEDALLION_ERROR_REASON_POLICY;
